spring.application.name=ats-system

spring.datasource.url=jdbc:postgresql://localhost:5432/ats
spring.datasource.username=ats
spring.datasource.password=ats

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
